version: 0.2

phases:

  pre_build:
    commands:
      - chmod a+x ./utils/*
      - eval $(./utils/aws-cli-assumerole.sh -r $ASSUME_ROLE_NAME)
      - export TF_WARN_OUTPUT_ERRORS=true
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Image tag is $IMAGE_TAG
  build:
    commands:
      - cd ./terraform
      - terraform init
      - terraform apply -auto-approve -var-file="terraform.tfvars" -var task_image_tag=$IMAGE_TAG
